# Generated by Django 6.0.3 on 2026-03-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amortization',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='container_unit',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='moq',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='n_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='qty_received',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit_price',
        ),
    ]
