# Generated by Django 6.0.3 on 2026-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_remove_purchaseorder_amortization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_term',
            field=models.CharField(choices=[('VAT Inclusive', 'VAT Inclusive'), ('Taxable', 'Taxable'), ('Non-taxable', 'Non-taxable'), ('Tax Exempt', 'Tax Exempt'), ('VAT Exclusive', 'VAT Exclusive'), ('Zero-Rated', 'Zero-Rated')], default='VAT Inclusive', max_length=50),
        ),
    ]
