# Generated by Django 6.0.3 on 2026-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_purchaseorder_batch_id_alter_purchaseorder_tax_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
