# Generated by Django 6.0.3 on 2026-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_customerorder_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='zone_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
