# Generated by Django 6.0.3 on 2026-03-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_locationmaster_capacity_locationmaster_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_zone',
            field=models.CharField(blank=True, help_text='Primary storage location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('RAW', 'Raw Materials'), ('CON', 'Consumables'), ('FG', 'Finished Goods'), ('PK', 'Packaging Materials'), ('SCRAP', 'Scrap/Waste')], default='RAW', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('KGS', 'Kilograms'), ('MTR', 'Meters'), ('SET', 'Full Set'), ('BOX', 'Boxes'), ('ROLL', 'Rolls')], default='PCS', max_length=10),
        ),
    ]
