# Generated by Django 6.0.3 on 2026-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_item_default_zone_alter_item_category_alter_item_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text="Supplier's physical address for routing", null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate vendor'),
        ),
    ]
