# Generated by Django 6.0.3 on 2026-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_supplier_address_supplier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_code',
            field=models.CharField(blank=True, help_text='Client ID / Barcode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_transport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='route_code',
            field=models.CharField(blank=True, help_text='Logistics Routing Zone (e.g. METRO MANILA, NORTH)', max_length=100, null=True),
        ),
    ]
