# Generated by Django 6.0.3 on 2026-04-06 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_contact_contact_code_contact_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True, verbose_name='Machine Serial/Code')),
                ('name', models.CharField(max_length=200, verbose_name='Machine Name/Model')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Building', 'Building / Incomplete'), ('Available', 'Available / Complete'), ('Partial', 'Partial / Missing Parts'), ('Dismantled', 'Dismantled / Cannibalized'), ('Deployed', 'Deployed to Client')], default='Building', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Assemble', 'Assemble (Install to Machine)'), ('Dismantle', 'Dismantle (Remove from Machine)')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Inventory.machineasset')),
                ('material_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_usages', to='Inventory.materialtag')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
