# Generated by Django 6.0.3 on 2026-04-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_alter_emailroute_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailroute',
            name='event_name',
            field=models.CharField(choices=[('TEST_ALERT', 'System Test & Diagnostics'), ('LOW_STOCK', 'Low Stock / Critical Level Alert'), ('PO_APPROVAL', 'Purchase Order Approval Request'), ('NEW_USER', 'New User Registration Alert'), ('EXPIRING_STOCKS', 'Expiring Materials Warning (30 Days)'), ('SECURITY_ALERT', 'Security: Multiple Failed Login Attempts'), ('QC_FAILED', 'Quality Control: Material Rejected/Failed Alert'), ('LATE_DELIVERY', 'Logistics: Overdue / Late Delivery Alert'), ('STOCK_CORRECTION', 'Inventory: Manual Stock Override/Correction Alert'), ('NEW_DELIVERY_REQ', 'Logistics: New Movement Slip / Transfer Request'), ('NEW_MATERIAL_REQ', 'Warehouse: New Material Request Submitted'), ('ASSEMBLY_COMPLETED', 'Production: Machine Assembly Completed'), ('STOCK_MOVE', 'Inventory: Item Location Transfer Alert')], max_length=50, unique=True, verbose_name='Notification Event'),
        ),
    ]
