# Generated by Django 6.0.3 on 2026-04-10 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_alter_emailroute_event_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CUSTOMER_ORDER', 'Customer Order'), ('PURCHASE_ORDER', 'Purchase Order'), ('RECEIVING', 'Receiving & Inspection'), ('INV_REQUEST', 'Inventory Request'), ('INV_PROCESSING', 'Inventory Processing'), ('INV_INQUIRY', 'Inventory Inquiry'), ('ASSET_WIP', 'Asset & WIP Management'), ('USER_MASTER', 'User Master'), ('SYSTEM_ANALYTICS', 'System Analytics'), ('SYS_CONFIG', 'System Configuration')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the user to grant access', max_length=254, unique=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_modules', models.ManyToManyField(blank=True, related_name='authorized_users', to='Inventory.systemmodule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
