# Generated by Django 6.0.3 on 2026-04-13 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_systemmodule_useraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='email',
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
