# Generated by Django 6.0.3 on 2026-04-13 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_remove_useraccess_email_alter_useraccess_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailroute',
            name='target_emails',
        ),
        migrations.AddField(
            model_name='emailroute',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Select users who should receive this notification.', related_name='email_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
