# Generated by Django 6.0.3 on 2026-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_remove_emailroute_target_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='level',
            field=models.CharField(default='info', max_length=20),
        ),
    ]
