# Generated by Django 6.0.3 on 2026-04-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_item_brand_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailroute',
            name='event_name',
            field=models.CharField(choices=[('TEST_ALERT', 'System Test & Diagnostics'), ('LOW_STOCK', 'Low Stock / Critical Level Alert'), ('PO_APPROVAL', 'Purchase Order Approval Request'), ('NEW_USER', 'New User Registration Alert'), ('EXPIRING_STOCKS', 'Expiring Materials Warning (30 Days)'), ('SECURITY_ALERT', 'Security: Multiple Failed Login Attempts'), ('QC_FAILED', 'Quality Control: Material Rejected/Failed Alert'), ('LATE_DELIVERY', 'Logistics: Overdue / Late Delivery Alert'), ('STOCK_CORRECTION', 'Inventory: Manual Stock Override/Correction Alert'), ('NEW_DELIVERY_REQ', 'Logistics: New Movement Slip / Transfer Request'), ('NEW_MATERIAL_REQ', 'Warehouse: New Material Request Submitted'), ('ASSEMBLY_COMPLETED', 'Production: Machine Assembly Completed'), ('STOCK_MOVE', 'Inventory: Item Location Transfer Alert'), ('STOCK_OUT', 'Inventory: Stock Issuance / Deduction Alert'), ('QC_PENDING', 'Quality Control: Pending Inspections Reminder'), ('AGING_REQUESTS', 'Warehouse: Unfulfilled/Aging Requests Alert'), ('DEAD_STOCK', 'Finance: Dead / Slow-Moving Stock Alert')], max_length=50, unique=True, verbose_name='Notification Event'),
        ),
    ]
