# Generated by Django 6.0.3 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_item_updated_at_alter_emailroute_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='cust_po_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
