# Generated by Django 6.0.3 on 2026-04-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_customerorder_cust_po_no_customerorder_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'Truck'), ('Van', 'Van'), ('Motorcycle', 'Motorcycle')], max_length=50)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coding_day', models.CharField(choices=[('Monday', 'Monday (1, 2)'), ('Tuesday', 'Tuesday (3, 4)'), ('Wednesday', 'Wednesday (5, 6)'), ('Thursday', 'Thursday (7, 8)'), ('Friday', 'Friday (9, 0)'), ('None', 'None (Exempted)')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Transit', 'In Transit'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
