# Generated by Django 6.0.3 on 2026-05-05 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_remove_emailroute_target_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailroute',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='email_subscriptions', through='Inventory.NotificationSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
