# Generated by Django 6.0.3 on 2026-05-06 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0025_emailroute_target_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_no', models.CharField(max_length=50, unique=True)),
                ('rma_type', models.CharField(choices=[('CUSTOMER_RETURN', 'Customer Return (Inbound)'), ('SUPPLIER_RETURN', 'Return to Vendor (Outbound)')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Authorization'), ('Received', 'Received in Quarantine'), ('Inspected', 'Inspected (QC Done)'), ('Resolved', 'Resolved (Closed)'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_returns', to='Inventory.contact')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtv_returns', to='Inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RMAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_returned', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('Good', 'Good Condition (Wrong Delivery)'), ('Defective', 'Defective / Damaged'), ('Expired', 'Expired / Near Expiry')], default='Defective', max_length=20)),
                ('disposition', models.CharField(choices=[('Pending', 'Pending QC Decision'), ('Restock', 'Restock to Main Warehouse'), ('Scrap', 'Scrap / Dispose'), ('RTV', 'Return to Vendor / Supplier')], default='Pending', max_length=20)),
                ('material_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.materialtag')),
                ('rma_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_items', to='Inventory.rmarequest')),
            ],
        ),
    ]
