# Generated by Django 6.0.3 on 2026-05-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_rmarequest_rmaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmaitem',
            name='financial_resolution',
            field=models.CharField(choices=[('Pending', 'Pending Resolution'), ('Refund', 'Refund to Customer'), ('Replace', 'Replace Item (Zero Cost)'), ('Credit Memo', 'Credit Memo (For Supplier)'), ('Write-Off', 'Write-Off (Company Loss)')], default='Pending', max_length=30),
        ),
    ]
