# Generated by Django 6.0.3 on 2026-05-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0027_rmaitem_financial_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmaitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
