# Generated by Django 6.0.3 on 2026-05-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0028_rmaitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmaitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
