# Generated by Django 6.0.3 on 2026-05-06 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0029_rmaitem_refund_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending Arrival (On the way)'), ('Arrived', 'Arrived at Dock (Ready for Dispatch)'), ('Dispatched', 'Dispatched to Customer'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossdock_allocations', to='Inventory.purchaseorderitem')),
                ('so_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossdock_sources', to='Inventory.customerorder')),
            ],
        ),
    ]
