# Generated by Django 6.0.3 on 2026-05-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0030_crossdockallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossdockallocation',
            name='rma_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_allocs', to='Inventory.rmaitem'),
        ),
    ]
