# Generated by Django 6.0.3 on 2026-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0031_crossdockallocation_rma_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='picked_qty',
            field=models.IntegerField(default=0),
        ),
    ]
