# Generated by Django 6.0.3 on 2026-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0032_customerorder_picked_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck instead of deleting'),
        ),
        migrations.AddField(
            model_name='item',
            name='upc_barcode',
            field=models.CharField(blank=True, help_text='Supplier Barcode (Optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Weight per unit in KG', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('RAW', 'Raw Materials'), ('CON', 'Consumables'), ('FG', 'Finished Goods'), ('PK', 'Packaging Materials'), ('SCRAP', 'Scrap/Waste')], default='RAW', max_length=50),
        ),
    ]
